"""AESDK package."""

from ._version import __version__
from .agent import (
    AgentContext,
    AIPassportResult,
    AnalysisRunResult,
    IntakeResult,
    InteractionLogResult,
    PreflightResult,
    PrepareResult,
    ReviewDiffResult,
    RuntimeMetadataResult,
    SetupResult,
    agent_context,
    append_interaction_log,
    build_ai_passport,
    build_ai_passport_summary,
    draft_pap,
    intake_prompt,
    intake_task,
    prepare,
    preflight,
    run_analysis,
    run_setup,
    write_ai_passport,
    write_claude_runtime_metadata,
    write_codex_runtime_metadata,
    write_copilot_runtime_metadata,
    write_review_diff,
    write_workflow_report,
)
from .data import (
    AssumptionCheck,
    DataProfile,
    DataScanResult,
    OLSDiagnosticsReport,
    ols_assumption_report,
    resolve_data_path,
    scan_data,
)
from .knowledge import get_knowledge_pack

__all__ = [
    "AgentContext",
    "AIPassportResult",
    "AnalysisRunResult",
    "AssumptionCheck",
    "DataProfile",
    "DataScanResult",
    "OLSDiagnosticsReport",
    "IntakeResult",
    "InteractionLogResult",
    "PreflightResult",
    "PrepareResult",
    "ReviewDiffResult",
    "RuntimeMetadataResult",
    "SetupResult",
    "__version__",
    "agent_context",
    "append_interaction_log",
    "build_ai_passport",
    "build_ai_passport_summary",
    "draft_pap",
    "get_knowledge_pack",
    "intake_prompt",
    "intake_task",
    "ols_assumption_report",
    "prepare",
    "preflight",
    "resolve_data_path",
    "run_analysis",
    "run_setup",
    "scan_data",
    "write_ai_passport",
    "write_claude_runtime_metadata",
    "write_codex_runtime_metadata",
    "write_copilot_runtime_metadata",
    "write_review_diff",
    "write_workflow_report",
]
